CREATE TABLE captcha_data (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    verification_token TEXT UNIQUE NOT NULL,
    target_position INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
